### ISSUE TITLE
No Go Client

### ISSUE THREAD

**Issue by sandrom** [griddb/griddb#16]
It really needs one. Dont have the time for that though. Also gccgo inflicts probably a bit much of a performance penalty, to be really useful wrapping the c library, but it might be a starting point.

**Comment by knonomura** [comment]
I'm glad to hear a request for Go Client.
For what purpose would you like to use Go Client ?

**Comment by sandrom** [comment]
@knonomura Using it in go projects of course. It would be possible to somehow connect the c library, but as said, then it would require gccgo and unfortunately it also means a more complicated build chain, which generally doesnt help acceptance much. We do a lot of IoT, so griddb sounds interesting here.

**Comment by knonomura** [comment]
Thank you for your reply.

Would using gc instead of gccgo to compile GridDB application be adequate for your need?
If so, I think Go Client derived from C Client and SWIG (Simplified Wrapper and Interface Generator) 
like Python Client would be useful.

I'd like to open-source many programming language client for GridDB and looking forward to contributions from everyone.

**Comment by sandrom** [comment]
@knonomura cgo or gccgo are a viable quick-start option, but they are really cumbersome and add a lot of problems and unfortunately for high load server applications also overhead, that can not really be ignored in production. cgo has quite a high latency for calls, while gccgo has a lower one, but messes up on other fronts, which make it all worse (quite strongly increased memory usage especially)
with cgo its usually less of a problem, when you can batch your calls heavily (see librdkafka, where this happens), but otherwise its quite expensive. For getting something stable out quickly, it might be an option, but it wouldnt be a long term solution, especially as cgo kinda fucks up go's fibers (blocks a thread until the c call returns) on top of it.
hope i'll have time beside family and work to investigate there enough, but most likely best place would be to get something going using cgo with a decent go frontend, so that the backend can be replaced by go native after that.

**Comment by sandrom** [comment]
main reason for cgo over gccgo would be that it will support the newest go runtimes at least. gccgo is usually not very helpful in server applications (but can be the better choice for special architectures, as some are only supported by it)

**Comment by knonomura** [comment]
Thank you for the information about cgo and gccgo.
