### ISSUE TITLE
error carga nuevo usuario, rol encargado

### ISSUE THREAD

**Issue by mbustaadmin** [griddb/griddb#281]
srry

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by mbustaadmin** [comment]
I am sorry

**Comment by jerichoECKO** [comment]
Hello can you help me recover my account? 

Enviado desde Yahoo Mail para Android 
 
  El mar., 16 de jun. de 2020 a la(s) 10:05 p. m., mbustaadmin<notifications@github.com> escribió:   


I am sorry

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
