### ISSUE TITLE
modif visual OT

### ISSUE THREAD

**Issue by mbustaadmin** [griddb/griddb#282]
Al clickear imprimir en una OT
http://inpapp01/OTPDF/?OTsID=3
Al lado del legajo, que muestre el apellido en lugar de YZ3CJ_...
![image](https://user-images.githubusercontent.com/65364635/84529190-657e7380-acb7-11ea-8734-1d2bd0e72933.png)

**Comment by mbustaadmin** [comment]
Al igual que en vista de empleados:
![image](https://user-images.githubusercontent.com/65364635/84529383-bee6a280-acb7-11ea-9f01-13907d81ee2a.png)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
