### ISSUE TITLE
Visual Lista de Procesos

### ISSUE THREAD

**Issue by mbustaadmin** [griddb/griddb#283]
No scrollea para mostrar todos los procesos. Tambien estaria bueno achicar un poco los renglones para ver más. Entran 9 visibles, son como 15 o 20 los productos que más tienen.
![image](https://user-images.githubusercontent.com/65364635/84534772-ec841980-acc0-11ea-9439-7e60479dd0ae.png)

**Comment by mbustaadmin** [comment]
Mismo issue en Listado Procedimiento.
![image](https://user-images.githubusercontent.com/65364635/84537132-906fc400-acc5-11ea-9617-50b8402ae562.png)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
