### ISSUE TITLE
I have a problem with a codein python

### ISSUE THREAD

**Issue by ACostadinero** [griddb/griddb#286]
I am trying to make a text game in python and when I enter the thing i want to see it always goes in order. This is my code:
import random
import time
import cmd 
import textwrap
import sys
import os

name = ''
choice = ''
x = 0
choice2 = ''

print('What is your name?')
name = input('>' )

##INTRO##
print('Hello ' + name + ' !')
time.sleep(1)

speech1 = "You are sent to the Baron`s Masion to see who killed him\n"
speech2 = "There is the Baron`s family trying to discover his cause of death\n"
speech3 = "You arrive there and start to question the family members"
for character in speech1:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(0.03)
for character in speech2:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(0.03)
for character in speech3:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(0.03)
time.sleep(4)

os.system('clear')

speech4 = "Who do you want interrogate the first person?\n"
speech5 = "Coco, Gioanta, Ryky\n"
for character in speech4:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(0.03)
for character in speech5:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(0.03)

choice = input('> ')

if choice == "Coco" or "coco":
    print("Coco: I was with a firend")
    choice = input('> ')
elif choice == "Gioanta" or "gioanta":
   print("Gioanta: I was at home") 
    choice = input('> ')
elif choice == "Ryky" or "ryky":
    print("Ryky: I was in the park")  
    choice = input('> ')

And if the first input is ryky it show  "Coco: I was with a firend"
then every thing i input shows "Gioanta: I was at home" and then "Ryky: I was in the park"
Thank you in advance

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

I guess it might be useful for you to use stackoverflow.
https://stackoverflow.com/

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
