### ISSUE TITLE
Android Studio has a problem

### ISSUE THREAD

**Issue by Javohir27** [griddb/griddb#287]
Hi, my name is Javohir. In Android Studio, I wanted to bring my app to the * .apk file view via the build menu. But as the process went on, it stopped. Then the problem arose. I tried several times myself and it didn’t help to solve the problem anyway. I haven’t been able to solve this problem in a few decades. I left a copy of the error message below. I need help.
Executing tasks: [:app:assembleDebug] in project C:\Users\User_name\AndroidStudioProjects\JustJava

Starting Gradle Daemon…
Gradle Daemon started in 7 s 340 ms

Task :app:preBuild UP-TO-DATE
Task :app:preDebugBuild UP-TO-DATE
Task :app:generateDebugBuildConfig UP-TO-DATE
Task :app:compileDebugAidl NO-SOURCE
Task :app:compileDebugRenderscript NO-SOURCE
Task :app:javaPreCompileDebug UP-TO-DATE
Task :app:generateDebugResValues UP-TO-DATE
Task :app:generateDebugResources UP-TO-DATE
Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
Task :app:extractDeepLinksDebug UP-TO-DATE
Task :app:processDebugManifest UP-TO-DATE
Task :app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

** What went wrong:*
Execution failed for task ‘:app:mergeDebugResources’.
> Multiple task action failures occurred:

A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade*

 > AAPT2 aapt2-4.0.0-6051327-windows Daemon #4: Daemon startup failed*
   Please check if you installed the Windows Universal C Runtime.*
   This should not happen under normal circumstances, please file an issue if it does.*
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade*

 > AAPT2 aapt2-4.0.0-6051327-windows Daemon #5: Daemon startup failed*
   Please check if you installed the Windows Universal C Runtime.*
   This should not happen under normal circumstances, please file an issue if it does.*
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade*

 > AAPT2 aapt2-4.0.0-6051327-windows Daemon #3: Daemon startup failed*
   Please check if you installed the Windows Universal C Runtime.*
   This should not happen under normal circumstances, please file an issue if it does.*
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade*

 > AAPT2 aapt2-4.0.0-6051327-windows Daemon #6: Daemon startup failed*
   Please check if you installed the Windows Universal C Runtime.*
   This should not happen under normal circumstances, please file an issue if it does.*
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade*

 > AAPT2 aapt2-4.0.0-6051327-windows Daemon #8: Daemon startup failed*
   Please check if you installed the Windows Universal C Runtime.*
   This should not happen under normal circumstances, please file an issue if it does.*
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade*

 > AAPT2 aapt2-4.0.0-6051327-windows Daemon #7: Daemon startup failed*
   Please check if you installed the Windows Universal C Runtime.*
   This should not happen under normal circumstances, please file an issue if it does.*
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade*

 > AAPT2 aapt2-4.0.0-6051327-windows Daemon #9: Daemon startup failed*
   Please check if you installed the Windows Universal C Runtime.*
   This should not happen under normal circumstances, please file an issue if it does.*
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade*

 > AAPT2 aapt2-4.0.0-6051327-windows Daemon #10: Daemon startup failed*
   Please check if you installed the Windows Universal C Runtime.*
   This should not happen under normal circumstances, please file an issue if it does.*
** Try:*
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

** Get more help at https://help.gradle.org*

BUILD FAILED in 1m 14s
7 actionable tasks: 1 executed, 6 up-to-date

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
I'll close this issue as it is not related to this repository.
