### ISSUE TITLE
GridDB v4.5 on CentOS8 installation failure

### ISSUE THREAD

**Issue by tsekino62** [griddb/griddb#288]
OS: CentOS Linux release 8.2.2004

`/usr/bin/python` が無い？ようなエラーメッセージが出るので、ご教示のほどよろしくお願い致します。

```
$ sudo rpm -ivh --test https://github.com/griddb/griddb/releases/download/v4.5.0/griddb-4.5.0-1.linux.x86_64.rpm
Retrieving https://github.com/griddb/griddb/releases/download/v4.5.0/griddb-4.5.0-1.linux.x86_64.rpm
error: Failed dependencies:
        /usr/bin/python is needed by griddb-4.5.0-1.linux.x86_64
````

pythonはあり、Version 3.6.8が入っています。

```
$ /usr/bin/python --version
Python 3.6.8
```

------

OS: CentOS Linux release 8.2.2004

installation failure GridDB on CentOS 8.
Error Message say `/usr/bin/python` is missing(?)
Please Help me...

```
$ sudo rpm -ivh --test https://github.com/griddb/griddb/releases/download/v4.5.0/griddb-4.5.0-1.linux.x86_64.rpm
Retrieving https://github.com/griddb/griddb/releases/download/v4.5.0/griddb-4.5.0-1.linux.x86_64.rpm
error: Failed dependencies:
        /usr/bin/python is needed by griddb-4.5.0-1.linux.x86_64
````

But, I had Python v3.6.8.

```
$ /usr/bin/python --version
Python 3.6.8
```

tahnks.

拙い英語ですが伝わっていただければ幸いです。。。

**Comment by AnggaSuherman** [comment]
Hi, can you try with CentOS 7.6?
Or try the following: https://stackoverflow.com/questions/61622815/i-get-error-when-i-try-to-install-griddb-database

**Comment by tsekino62** [comment]
I try CentOS 7.8. 
And, i can install GridDB!
Thanks!

```
$ cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
```

Will you support CentOS 8?

My team will update server to CentOS8.
----

CentOS 7.8で試したところインストールできました。
ありがとうございます。

今後、CentOS8をサポートする予定はありますか？
CentOS8に変える予定なので。。。

**Comment by chiendh** [comment]
@tsekino62 

I have comment.
Could you please try to use python2 on CentOS 8 ?

**Comment by tsekino62** [comment]
I’ve tried to use python2.
I use `alternatives` command.

**Comment by tsekino62** [comment]
Python2で試した時の情報を展開します。

I'll tell you the log when I tried to use python2.

```
# alternatives --config python
There are 3 programs which provide 'python'.
  Selection    Command
-----------------------------------------------
*  1           /usr/libexec/no-python
 + 2           /usr/bin/python3
   3           /usr/bin/python2
Enter to keep the current selection[+], or type selection number: 3
# exit
$ /usr/bin/python --version
Python 2.7.17
$ sudo rpm -ivh --test https://github.com/griddb/griddb/releases/download/v4.5.0/griddb-4.5.0-1.linux.x86_64.rpm
Retrieving https://github.com/griddb/griddb/releases/download/v4.5.0/griddb-4.5.0-1.linux.x86_64.rpm
error: Failed dependencies:
        /usr/bin/python is needed by griddb-4.5.0-1.linux.x86_64
```

**Comment by AnggaSuherman** [comment]
> I try CentOS 7.8.
> And, i can install GridDB!
> Thanks!
> 
> ```
> $ cat /etc/redhat-release 
> CentOS Linux release 7.8.2003 (Core)
> ```
> 
> Will you support CentOS 8?
> 
> My team will update server to CentOS8.
> 
> CentOS 7.8で試したところインストールできました。
> ありがとうございます。
> 
> 今後、CentOS8をサポートする予定はありますか？
> CentOS8に変える予定なので。。。

@tsekino62 本RPMパッケージはCentOS7で確認しています。
CentOS8向けのRPMは今年秋くらいに提供する計画です。

The current RPM package is tested with CentOS7. Support for Centos8 will be around fall this year.

**Comment by tsekino62** [comment]
@AnggaSuherman 

ご回答ありがとうございます。
では、CentOS8版が出たら改めて試させていただきます。

thanks for your reply.
OK, I'll try RPM package supported for CentOS8.

**Comment by knonomura** [comment]
@tsekino62 
Python2が必要になりますが、v4.5.2にてCentOS8向けのRPMをリリースしました。
お試しください。

RPM(V4.5.2) for CentOS8 has been released.
