### ISSUE TITLE
Alexa Dextr Flex Skill

### ISSUE THREAD

**Issue by DrVoIP** [griddb/griddb#302]
Goals:
1 - Enable Connect to be used as both a call center and as a hosted PBX by creating an outbound dial solution for field personnel and non agent users.
2- Create a voice based real time metric reporting option

Sample commands using keyword "dial" and "report"
Alexa ask Dextr to DIAL contactName
Alexa ask Dextr to DIAL destinationNumber
Alexa ask Dextr to DIAL agentName
Alexa ask Dextr to DIAL conference, hold, transfer
Alexa ask Dextr to REPORT status of queueName
Alexa ask Dextr to REPORT status of agentName
Alexa ask Dextr to REPORT summary

It may require an Alexa device for each remote user, but they can access from Alexa App on smartphone.   I see some GitHub repositories that have SMS and Dial functions so others have been down this road.  I am researching requirements and will update.  The Alexa app would eliminate our need to create a smartphone app for IOS and Android and to avoid the maintenance issues of code updates as the OS changes.

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issue as it is not related to griddb/griddb repository.
