### ISSUE TITLE
WHERE conditions is not working

### ISSUE THREAD

**Issue by hrkuma** [griddb/griddb#308]
**Describe the bug**
The issue happens query having multiple ANDed WHERE conditions.
If I execute two query "SELECT * WHERE A AND B" and "SELECT * WHERE B AND A", I could not get the same results.
It happens under the version of v4.5.1 for both GriddB server and c_client library. (It is same for other versions > 4.2.1.)
However when I execute the same query under 4.2.1 GridDB (+ v4.2.0 c_client library), I can get  expected output.

**To Reproduce**
We can reproduce this issue using below program.
<pre>
#include "gridstore.h"
#include <stdlib.h>
#include <stdio.h>

typedef struct {
        int c1;
} Test;

GS_STRUCT_BINDING(Test, GS_STRUCT_BINDING_KEY(c1, GS_TYPE_INTEGER));

static void execute(GSCollection *col, char *tql)
{
        GSQuery *query; GSRowSet *rs; GSResult ret; Test test;
        ret = gsQuery(col, tql, &query); if (!GS_SUCCEEDED(ret)) exit(-1);
        ret = gsFetch(query, GS_TRUE, &rs); if (!GS_SUCCEEDED(ret)) exit(-1);
        printf("query: %s\n", tql);
        while (gsHasNextRow(rs)) {
                gsGetNextRow(rs, &test);
                ret = gsUpdateCurrentRow(rs, &test); if (!GS_SUCCEEDED(ret)) exit(-1);
                printf(" c1=%d\n", test.c1);
        }
}

void main(void)
{
        GSGridStore *store; GSCollection *col; GSResult ret; Test test; int i;
        const GSPropertyEntry props[] = { { "notificationAddress", "239.0.0.1" },
                                          { "notificationPort", "31999" },
                                          { "clusterName", "griddbfdwTestCluster" },
                                          { "user", "admin" },
                                          { "password", "testadmin" } };
        const size_t propCount = sizeof(props) / sizeof(*props);

        gsGetGridStore(gsGetDefaultFactory(), props, propCount, &store);
        gsPutCollection(store, "test01", GS_GET_STRUCT_BINDING(Test), NULL, GS_FALSE, &col);
        gsSetAutoCommit(col, GS_FALSE);
        for (i=0; i <10; i++) {
          test.c1 = i; gsPutRow(col, NULL, &test, NULL);
        }
        gsCommit(col);
        execute(col, "SELECT * WHERE (c1 > 8) AND (c1 > 1)");
        execute(col, "SELECT * WHERE (c1 > 1) AND (c1 > 8)");
        gsCommit(col);
        gsCloseGridStore(&store, GS_TRUE);
}
</pre>

In 4.5.1 I got the following results.
<pre>
query: SELECT * WHERE (c1 > 8) AND (c1 > 1)
 c1=2
 c1=3
 c1=4
 c1=5
 c1=6
 c1=7
 c1=8
 c1=9
query: SELECT * WHERE (c1 > 1) AND (c1 > 8)
 c1=9
</pre>

**Expected behavior**
The result should be below.
<pre>
query: SELECT * WHERE (c1 > 8) AND (c1 > 1)
 c1=9
query: SELECT * WHERE (c1 > 1) AND (c1 > 8)
 c1=9
</pre>

**Comment by knonomura** [comment]
Thank you so much for your usage and report.
I'll check it.

**Comment by knonomura** [comment]
Sorry for late reply.

This issue turned out to be due to updates for Composite Index.
I have fixed this issue by #316.
Could you please try v4.5.3 ?

**Comment by hrkuma** [comment]
Thank you for fixing and release a new version!

I could confirm fix in my environment.
