### ISSUE TITLE
Условная проверка валидности телефона

### ISSUE THREAD

**Issue by kostiantyn-leontiev** [griddb/griddb#313]
Нам необходимо проверять условную валидность телефона. Иногда люди вводят или ввели ранее что-то типа "1", система запомнила ЭТО в резульатате получаем вот такие запросы:
Замовлення №70; 07.01.21 15:51
Покупець: @null
Замовив: Milk Stout-2(=2,0*1)л
Адреса замовлення: Бульвар Леси Украинки 4 кв 82
Номер телефону: 1
Форма сплати: Термінал
Сума до сплати 180,00 грн.

Мы приспособились их отрабатывать, но чем дальше тем сложнее.
Предлагается либо дать форму, чтобы люди вводили правильно, либо написать шаблон, например (000) 000 0000. И проверять все под него.

Ну и продумать интерфейс для исправления ранее запомненных неправильных номеров.

Пока давай обсудим как лучше.

**Comment by nailbiter** [comment]
Please ignore this issue (and feel free to close it). This was intended to be added into another repository. Sorry for inconvenience.

**Comment by knonomura** [comment]
Thank you for your comment.
I close this issue.
