### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by Rodrigo-Carvajal** [griddb/griddb#327]
Hi, apparently someone was using my account...
My intentions aren't delete the repositorie cause I saw you put a lot of work in it.
So please, tell my an username to assign the autoritie of the repositorie and not delete it.
Have a nice day, hope your awnser ASAP.

**Comment by knonomura** [comment]
Thank you for your access.
Your issue is opened in griddb/griddb repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issue.
