### ISSUE TITLE
Determine All Sites where 3rd Party App is Added in SPO

### ISSUE THREAD

**Issue by sahucs06** [griddb/griddb#341]
**Is your feature request related to a problem? Please describe.**
In the classic SharePoint Admin center, you can find out the number of sites where a client-side SharePoint Framework application has been installed. However, this does not tell you which sites have the app installed. I thought SharePoint Online Management Shell (with pnp) would help here, but Get-PnPAppInstance has been deprecated, and Get-PnPApp does not seem to work.

**Describe the solution you'd like**
Looking some powershell script which I can run at tenant level and get the all the sites.

**Describe alternatives you've considered**

**Additional context**

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issue as it is not related to griddb/griddb repository.
