### ISSUE TITLE
gs_startnode -releaseUnusedFileBlocks

### ISSUE THREAD

**Issue by nordlings** [griddb/griddb#354]
**Describe the bug**

I have been changing (lowering) the expiration time on bunch of collections, (copied data over to a new time series collection).

This resulted in a much smaller data store but the size of the checkpoint file did not decrease.

Started the node with -releaseUnusedFileBlocks option which decreased the database size drastically. But over a days operation the size of the checkpoint file is now doubled compared to earlier.
After issuing the release start option once again the size is now four times the original size when no data had been expired.
Running auto expire in the config.

Can anyone understand how to correctly reduce the size of the database and keep it at a decent size?
I fear after one year operation, disk consumption will be ridiculous... and as of now I have no method to shrink else than starting fresh with an empty db...

**To Reproduce**
1. Start with a database in normal operation
2. Recreated the collections with 1 day expiration time (new name) and copy the data from old collection
3. Drop old collections
4. Now with a set collection with only 1day expiration time the store is pretty small.
5. Start gs_node with option -releaseUnusedFileBlocks
6. After a few hours the checkpoint file is back at size or even larger than before with still only 1 day of data in the store.

**Expected behavior**
A "non increasing" size of checkpoint file.

**Additional context**
During the day with normal operation when file increased there were no major changes to the database except for roughly 100 values per minute inserted to db.

Store is currently about 100MByte.
Checkpoint file grow up to about 2GByte second time I tried releasing unused blocks. Thats 20 times larger than the data store.

**Comment by nordlings** [comment]
I can also mention that I have developed an iot platform that is automatically re-creating containers if the specified expiration time is changed.

But right now after some basic tests it doesn't seem like the database size can be controlled this way. At least not until I know how to control the size of the checkpoint file.

I have created calculated measures that is calculating the daily growth of the database so that the expiration time can be adjusted "as we go" to find a size that fits the environment (size of hardrive) for a long term solution without need of regular db maintenance.

**Comment by knonomura** [comment]
Thank you for your usage.

How about not the file size but the disk usage about the checkpoint file ?
Could you please confirm the disk usage with "du" or "ls -s" command ?

And do you use block data compression function ?
- dataStore/storeCompressionMode: "COMPRESS" in gs_node.json
https://github.com/griddb/docs-en/blob/master/manuals/GridDB_FeaturesReference.md#block-data-compression

**Comment by nordlings** [comment]
Hi knonomura,
Confirming I am using "du" on the griddb data folder to pull the database size which now for roughly 200 signals with about 1min sample rate has comsumed 2.2GByte in 30days (~30GByte / year). The influx database I am running in parralell is about 1000th of that size...

And I alse see the same thing going on in the dev environment. This is where I tested to re-generate all containers with only 1 day expiration day which I would expect reducing the database size drastically but instead it sized up even more. 

![image](https://user-images.githubusercontent.com/78299773/134956998-d63175b4-8288-403a-a5b5-322fa579381d.png)

**Comment by knonomura** [comment]
>Store is currently about 100MByte.
>Checkpoint file grow up to about 2GByte second time I tried releasing unused blocks. 
>Thats 20 times larger than the data store.

Do you compare the total size of input row data and checkpont file (\*.dat) ?
The griddb data folder also includes transaction log (redo log) file (\*.log) .

Let me confirm about your test.

- GridDB version: 4.6.1 ?
- Interface: NoSQL(Java) or SQL(JDBC) or others ?
- GridDB Container type: collection container or timeseries container ?
https://github.com/griddb/docs-en/blob/master/manuals/GridDB_FeaturesReference.md#type

- The number of GridDB Container: 200 ?
- The size of row data: 100 bytes or 1KB or others ?

- Expiry release function: Row expiry release or Partition expiry release ?
https://github.com/griddb/docs-en/blob/master/manuals/GridDB_FeaturesReference.md#expiry-release-function

- Parameter
  - dataStore/storeBlockSize in gs_cluster.json:"64KB"(default) ?
  - checkpoint/checkpointInterval in gs_node.json:"60s"(default) ?

  https://github.com/griddb/docs-en/blob/master/manuals/GridDB_FeaturesReference.md#parameter

**Comment by nordlings** [comment]
Hi knonomura and thanks for replying... 
Let me try answering your questions inline below.

> Do you compare the total size of input row data and checkpont file (*.dat) ?
> The griddb data folder also includes transaction log (redo log) file (*.log) .
I compare the total storage of the data folder. But the big files are the .dat files.
![image](https://user-images.githubusercontent.com/78299773/136705384-4df0f1a4-102a-4743-be24-d7e4b13f3774.png)
I have seen a strange error message in the gsstartup.log file
![image](https://user-images.githubusercontent.com/78299773/136705431-8698ff51-0d2c-4555-b614-a2143e9a7994.png)
Every time there is an output written to the log this error message are presented which I would expect is some problem with the arm fork and I did not believe it had any this with the performance on the database.
> 
> Let me confirm about your test.
> 
> * GridDB version: 4.6.1 ?
**version 4.5.0-37163 CE. Was looking into upgrading but haven´t found a new fork for arm out there yet...
[](https://github.com/griddbnet/griddb_arm)**

> * Interface: NoSQL(Java) or SQL(JDBC) or others ?
**Both actually. Running mostly NoSQL using node client from node-red but also some more complex transactions using the web api to query SQL statements.**

> * GridDB Container type: collection container or timeseries container ?
**I have both types of tables but my iot sensors are stored in timeseries containers. Normal collections to store meta data for the sensors.**
>   https://github.com/griddb/docs-en/blob/master/manuals/GridDB_FeaturesReference.md#type
> * The number of GridDB Container: 200 ?
**about 200 timeseries containers, only a couple normal collections.**

> * The size of row data: 100 bytes or 1KB or others ?
**Sorry I am not sure I know how to answer that question. This is screenshot from my gs_stat output on the row data.**
![image](https://user-images.githubusercontent.com/78299773/136705231-bd00b45c-9b65-4e59-b739-ace75451b112.png)


> * Expiry release function: Row expiry release or Partition expiry release ?
**Row expiry release only**

>   https://github.com/griddb/docs-en/blob/master/manuals/GridDB_FeaturesReference.md#expiry-release-function
> * Parameter
>   
>   * dataStore/storeBlockSize in gs_cluster.json:"64KB"(default) ?
**64KB**

>   * checkpoint/checkpointInterval in gs_node.json:"60s"(default) ?
**60s**

>   
>   https://github.com/griddb/docs-en/blob/master/manuals/GridDB_FeaturesReference.md#parameter

**Comment by nordlings** [comment]
Hi Katsuhiko,I have ben running 1 day row expriation for evaLuation purpose but is not doing it anymore.What I did was “coverted” a roughly 30day database to containers with only 1 day row expiration time to see how the database behave so that I can confirm in the future that the database size can be controlled by changing this. The algorithm I used was copying data to a temporary container then remove the source container and copy the data back to a new container with the new exeration time set on it. But even after days of execution the size of the database did not go down even tough the expiration time was set to 1 day.I then ran gs_startnode -releaseUnusedFileBlocks to reduce the size of the database. The size did go down to nearly nothing, but after a few days of daily execution the size went up even futher than before the expiration time was changed. I have not played with the expiration time now for a while since I confirmed the database size could not be controlled this way. What I have discovered instead is that the size of the database is drastically increasing for small amount of data and I will be forced to leave this database shortly because the size increase.Green line is the closest thing I have to a production environment. It´s been swallowing roughly 3-5min values on 200 collections (about 10 of the collections store Boolean and string values that is only storing “changed” values) since end of august when I had a database corruption problem. The blue line is my dev. Environment storing the same data but this is where I played around with the row expiration time and as you see it moved from rougly 1GByte size to roughly 3.5GB even though I ran 1 day row expiration. During my develop last weeks it has been reconfigured with the sma parameters as the prod env so not 1 day expiration anymore. The yellow line is an instance of influx v2 database running in parralell swallowing the same data.Interesting is that I see doubling of the database size each time it changes. I am measuring the size by running Linux command “du” statement in the /data folder. I have also looked at the gs_stat output trying to understand where the data get consumed but have not been very successful doing that. Remember that I am running the arm-fork of v4.5 of griddb and that I might contain an error? The collections are all having the same simple structure:[["timestamp", griddb.Type.TIMESTAMP],["value", griddb.Type.DOUBLE]] My current gs_stat output is attached and belongs to the prod. environment which is now roughly 8.5Gbyte size. BR.H  Sent from Mail for Windows From: Katsuhiko NonomuraSent: Monday, 18 October 2021 02:40To: griddb/griddbCc: Henrik Nordling; AuthorSubject: Re: [griddb/griddb] gs_startnode -releaseUnusedFileBlocks (#354) Thank you for the detailed information.I'll check this issue.I understand as follows:You compare the chechpoint file size and the store size in gs_stat output1 day expiration timeAnd if possilbe, could you please provide me the schema for timeseries container ?Java Example:class Point {        @RowKey Date timestamp;        boolean active;        double voltage;} Python Example:        [["timestamp", griddb.Type.TIMESTAMP],         ["active", griddb.Type.BOOL],         ["voltage", griddb.Type.DOUBLE]],—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mrgunjan** [comment]
M
