### ISSUE TITLE
Box-Shadow of class="col-lg-4 "

### ISSUE THREAD

**Issue by Ajay-Dhangar** [griddb/griddb#388]
**`class="col-lg-4 "`  element is not looking Good**
I have seen your site and checked but  I find one issue in` col-lg` elements is not looking good.

**Describe the solution I'm like**

apply this CSS for example.
```
.col-lg-4{
    text-align: center;
    margin: 24px;
    padding: 36px 24px 40px 24px;
    border-radius: 7px;
    background-color: #fff;
    box-shadow: 0 0 0 1px rgba(0, 0, 0, .15), 0 2px 3px 0 rgba(0, 0, 0, .1);
}
```
```
/*  ====== Mobile ======*/

@media screen and (max-width:680px) {
.col-lg-4 {
        padding: 5px;
        display: block;
    }
}
```

**Make sure this is good for your site**

**For Example **
- Desktop Size:
![image](https://user-images.githubusercontent.com/99037494/193386014-0d8487fb-4071-4dc1-9850-3c11fc0804f5.png)

- Mobile size:
 
![image](https://user-images.githubusercontent.com/99037494/193386095-be280c0b-0ba5-4456-ac97-9f0cbd3dbc01.png)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb repository,
but I guess it is another topic.
So I close it.
