### ISSUE TITLE
css search engine animation 

### ISSUE THREAD

**Issue by Vikasmaury** [griddb/griddb#389]
<html>
<body>

  | <!DOCTYPE html>
-- | --
  | <html>
  | <head>
  | <meta charset="utf-8">
  | <meta name="viewport" content="width=device-width, initial-scale=1">
  | <title>Effect</title>
  |  
  | <style>
  | @import url('https://font.googleapis.com/css2? family=Numto+Sans:wght@200&display=swap');
  | :root
  | {
  | --font-style: 'Nunito Sans', sans-serif;
  | }
  |  
  | *
  | {
  |  
  | padding: 0;
  | margin: 0;
  | }
  |  
  | html,
  | body
  | {
  | font-family: var(--font-style);
  | width: 100%;
  | height: 100%%;
  | background-color: #2A2734;
  | }
  | input
  | {
  | position: absolute;
  | top: 50%;
  | left: 50%;
  | transform: translate(-50%, -50%);
  | color: white;
  | font-size: 16px;
  | background: transparent;
  | width: 25px;
  | height: 25px;
  | padding: 10px;
  | border: solid 3px #9A86FD;
  | outline: none;
  | border-radius: 35px;
  | transition: all	0.5s;
  | box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 #9A86FD;
  | }
  |  
  | input::placeholder
  | {
  | color: #efefef;
  | opacity: 0;
  | transition: opacity 150ms ease-out;
  | }
  |  
  | input:focus::placeholder
  | {
  | opacity: 1;
  |  
  | }
  | input:hover
  | {
  | box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 #FFB870;
  | }
  | input:focus,
  | input:not(:placeholder-shown)
  | {
  | width: 250px;
  | box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 #FFB870;
  |  
  | }
  | </style>
  | </head>
  | <body>
  |  
  | <div class="searsh">
  | <input type="text" name="Search"  placeholder="Search . . ." required>
  | </div>
  |  
  | </body>
  | </html>

</body>
</html>
<html>
<body>

  | <!DOCTYPE html>
-- | --
  | <html>
  | <head>
  | <meta charset="utf-8">
  | <meta name="viewport" content="width=device-width, initial-scale=1">
  | <title>Effect</title>
  |  
  | <style>
  | @import url('https://font.googleapis.com/css2? family=Numto+Sans:wght@200&display=swap');
  | :root
  | {
  | --font-style: 'Nunito Sans', sans-serif;
  | }
  |  
  | *
  | {
  |  
  | padding: 0;
  | margin: 0;
  | }
  |  
  | html,
  | body
  | {
  | font-family: var(--font-style);
  | width: 100%;
  | height: 100%%;
  | background-color: #2A2734;
  | }
  | input
  | {
  | position: absolute;
  | top: 50%;
  | left: 50%;
  | transform: translate(-50%, -50%);
  | color: white;
  | font-size: 16px;
  | background: transparent;
  | width: 25px;
  | height: 25px;
  | padding: 10px;
  | border: solid 3px #9A86FD;
  | outline: none;
  | border-radius: 35px;
  | transition: all	0.5s;
  | box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2), 0 6px 20px 0 #9A86FD;
  | }
  |  
  | input::placeholder
  | {
  | color: #efefef;
  | opacity: 0;
  | transition: opacity 150ms ease-out;
  | }
  |  
  | input:focus::placeholder
  | {
  | opacity: 1;
  |  
  | }
  | input:hover
  | {
  | box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 #FFB870;
  | }
  | input:focus,
  | input:not(:placeholder-shown)
  | {
  | width: 250px;
  | box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 #FFB870;
  |  
  | }
  | </style>
  | </head>
  | <body>
  |  
  | <div class="searsh">
  | <input type="text" name="Search"  placeholder="Search . . ." required>
  | </div>
  |  
  | </body>
  | </html>

</body>
</html>

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb repository,
but I guess it is another topic.
So I close it.
