### ISSUE TITLE
Grecimar Rodriguez sección 11
Proyecto java 

### ISSUE THREAD

**Issue by Roro31389324** [griddb/griddb#393]
import java.io.IOException;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) throws IOException {
        Scanner sc = new Scanner(System.in);
        String texto;
        char caracter;
        int numeroDeVeces = 0;
        do {
            System.out.println("Introduce texto: ");
            texto = sc.nextLine();
        } while (texto.isEmpty());
        System.out.print("Introduce un carácter: ");
        caracter = (char) System.in.read();
        numeroDeVeces = contarCaracteres(texto, caracter);
        System.out.println("El caracter " + caracter + " aparece " + numeroDeVeces + " veces");                   
    }

    //calcular el número de veces que se repite un carácter en un String
    public static int contarCaracteres(String cadena, char caracter) {
        int posicion, contador = 0;
        //se busca la primera vez que aparece
        posicion = cadena.indexOf(caracter);
        while (posicion != -1) { //mientras se encuentre el caracter
            contador++;           //se cuenta
            //se sigue buscando a partir de la posición siguiente a la encontrada
            posicion = cadena.indexOf(caracter, posicion + 1);
        }
        return contador;
   }
}

**Comment by Peke5670** [comment]
> importar java.io.IOException; importar java.util.Scanner;
> 
> clase pública Principal {
> 
> ```
> public static void main(String[] args) throws IOException {
>     Scanner sc = new Scanner(System.in);
>     String texto;
>     char caracter;
>     int numeroDeVeces = 0;
>     do {
>         System.out.println("Introduce texto: ");
>         texto = sc.nextLine();
>     } while (texto.isEmpty());
>     System.out.print("Introduce un carácter: ");
>     caracter = (char) System.in.read();
>     numeroDeVeces = contarCaracteres(texto, caracter);
>     System.out.println("El caracter " + caracter + " aparece " + numeroDeVeces + " veces");                   
> }
> 
> //calcular el número de veces que se repite un carácter en un String
> public static int contarCaracteres(String cadena, char caracter) {
>     int posicion, contador = 0;
>     //se busca la primera vez que aparece
>     posicion = cadena.indexOf(caracter);
>     while (posicion != -1) { //mientras se encuentre el caracter
>         contador++;           //se cuenta
>         //se sigue buscando a partir de la posición siguiente a la encontrada
>         posicion = cadena.indexOf(caracter, posicion + 1);
>     }
>     return contador;
> ```
> 
> } }

Que hago jajaja

**Comment by Peke5670** [comment]
Cadena.intexOF

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb repository,
but I guess it is another topic.
So I close it.
