### ISSUE TITLE
when i create databases,how to swich the new database?

### ISSUE THREAD

**Issue by tom055** [griddb/griddb#395]
when i create new db.
CREATE DATABASE iotdb;
How to view all databases and switch to the specified database?
Look forward to your reply，think you

**Comment by knonomura** [comment]
Thank you for your question.

How to view all databases:
Unfortunately the current GridDB Community Edition has no method to view all databases.
We'll add it in our priority list.

How to switch to the specified database:
(JDBC Driver)
Please use Connection URL format with database name
like "jdbc:gs://(nodeAddress):(portNo)/(clusterName)/(databaseName)".

https://github.com/griddb/docs-en/blob/master/manuals/GridDB_JDBC_Driver_UserGuide.md#connection-url-format

(Java Client library)
Please use getGridStore() method with database property.

https://griddb.org/docs-en/manuals/GridDB_Java_API_Reference.html#GridStoreFactory.html__getGridStore(java.util.Properties)

**Comment by tom055** [comment]
i have solve swich the new database,
gs_sh>connect $cluster1 userDB
from https://www.griddb.net/en/docs/GridDB_OperationGuide.html#sec-1
(But this document is a little old. Can you provide me with the latest one)
Thank you for your reply，

**Comment by tom055** [comment]
已经解决这个问题了。非常感谢
