### ISSUE TITLE
GSConnectionException: [145029:JC_CONNECTION_TIMEOUT] Connection timed out on receiving

### ISSUE THREAD

**Issue by tom055** [griddb/griddb#397]
I have installed version 5.0 on the server ubuntu 18.04. The firewall has been closed. You can execute the following commands on the server:
java gsSample/Sample1 239.0.0.1 31999 myCluster admin admin
But when I try to connect with another computer, a connection timeout error occurs
```jsx
Properties props = new Properties();
props.setProperty("notificationAddress", "239.0.0.1");
props.setProperty("notificationPort", "31999");
props.setProperty("clusterName", "myCluster");
props.setProperty("user", "admin");
props.setProperty("password", "admin");
GridStore store = GridStoreFactory.getInstance().getGridStore(props);
Collection<String, Person> col = store.putCollection("col01", Person.class);
System.out.println("success!");
Person person = new Person();
person.setName("name011212");
person.setStatus(false);
person.setCount(1);
person.setLob(new byte[] { 65, 66, 67, 68, 69, 70, 71, 72, 73, 74 });
boolean update = true;
col.put(person);
col.commit();
System.out.println("success!");
```

The bug occurred in
```jsx
Collection<String, Person> col = store.putCollection("col01", Person.class);
```
gs_cluster.json
{
	"dataStore":{
		"partitionNum":128,
		"storeBlockSize":"64KB"
	},
	"cluster":{
		"clusterName":"myCluster",
		"replicationNum":2,
		"notificationAddress":"239.0.0.1",
		"notificationPort":20000,
		"notificationInterval":"5s",
		"heartbeatInterval":"5s",
		"loadbalanceCheckInterval":"180s"
	},
	"sync":{
		"timeoutInterval":"30s"
	},
	"transaction":{
		"notificationAddress":"239.0.0.1",
		"notificationPort":31999,
		"notificationInterval":"5s",
		"replicationMode":0,
		"replicationTimeoutInterval":"10s"
	},
	"sql":{
		"notificationAddress":"239.0.0.1",
		"notificationPort":41999,
		"notificationInterval":"5s"
	}
}

**Comment by tom055** [comment]
@knonomura whether the appication and GridDB server must on the same machine?

**Comment by knonomura** [comment]
First, could you please confirm the output of the following command on the machine running GridDB server ?
$ hostname -i

Is it the IP address of the machine ?

https://github.com/griddb/docs-en/blob/master/manuals/GridDB_QuickStartGuide.md#network-settings

**Comment by tom055** [comment]
I am sure it has been configured, Try the following methods to connect, but the connection fails
[root@localhost bin]# hostname -i
192.168.1.134

gs_stat:
{
    "checkpoint": {
        "backupOperation": 0,
        "duplicateLog": 0,
        "endTime": 1672031227807,
        "mode": "NORMAL_CHECKPOINT",
        "normalCheckpointOperation": 5480,
        "pendingPartition": 0,
        "periodicCheckpoint": "ACTIVE",
        "requestedCheckpointOperation": 0,
        "startTime": 1672031227794
    },
    "cluster": {
        "activeCount": 1,
        "applyRuleLimitTime": "2022-12-25T20:23:13.391-08:00",
        "autoGoal": "ACTIVE",
        "clusterName": "myCluster",
        "clusterRevisionId": "f27e3bcf-a87b-4317-a3e4-d51e52dcf8a3",
        "clusterRevisionNo": 65770,
        "clusterStatus": "MASTER",
        "currentRule": "Initial",
        "designatedCount": 1,
        "loadBalancer": "ACTIVE",
        "master": {
            "address": "127.0.0.1",
            "port": 10040
        },
        "nodeList": [
            {
                "address": "127.0.0.1",
                "port": 10040
            }
        ],
        "nodeStatus": "ACTIVE",
        "notificationMode": "MULTICAST",
        "partitionStatus": "NORMAL",
        "startupTime": "2022-12-22T01:01:52.391-08:00",
        "syncCount": 2
    },
    "currentTime": "2022-12-25T21:08:06-08:00",
    "performance": {
        "backgroundMinRate": 0.1,
        "backupCount": 0,
        "checkpointFileFlushCount": 128,
        "checkpointFileFlushTime": 0,
        "checkpointWrite": 0,
        "checkpointWriteCompressTime": 0,
        "checkpointWriteSize": 0,
        "checkpointWriteTime": 0,
        "currentTime": 1672031286424,
        "dataFileAllocateSize": 2162688,
        "dataFileSize": 2162688,
        "dataFileUsageRate": 0.6551724137931034,
        "expirationDetail": {
            "batchScanNum": 2000,
            "batchScanTotalNum": 0,
            "batchScanTotalTime": 0,
            "erasableExpiredTime": "",
            "estimatedBatchFree": 0,
            "estimatedErasableExpiredTime": "",
            "lastBatchFree": 0,
            "latestExpirationCheckTime": "Under measurement"
        },
        "logFileFlushCount": 256,
        "logFileFlushTime": 103,
        "numBackground": 0,
        "numConnection": 2,
        "numNoExpireTxn": 0,
        "numSession": 0,
        "numTxn": 0,
        "ownerCount": 128,
        "peakProcessMemory": 60887040,
        "poolBufferMemory": 589824,
        "processMemory": 60887040,
        "sqlNumConnection": 2,
        "sqlStoreSwapRead": 0,
        "sqlStoreSwapReadSize": 0,
        "sqlStoreSwapReadTime": 0,
        "sqlStoreSwapWrite": 0,
        "sqlStoreSwapWriteSize": 0,
        "sqlStoreSwapWriteTime": 0,
        "storeCompressionMode": "NO_BLOCK_COMPRESSION",
        "storeDetail": {
            "batchFreeMapData": {
                "storeMemory": 0,
                "storeUse": 0,
                "swapRead": 0,
                "swapWrite": 0
            },
            "batchFreeRowData": {
                "storeMemory": 0,
                "storeUse": 0,
                "swapRead": 0,
                "swapWrite": 0
            },
            "mapData": {
                "storeMemory": 131072,
                "storeUse": 458752,
                "swapRead": 2,
                "swapWrite": 0
            },
            "metaData": {
                "storeMemory": 458752,
                "storeUse": 458752,
                "swapRead": 7,
                "swapWrite": 0
            },
            "rowData": {
                "storeMemory": 0,
                "storeUse": 327680,
                "swapRead": 0,
                "swapWrite": 0
            }
        },
        "storeMemory": 589824,
        "storeMemoryLimit": 1073741824,
        "storeTotalUse": 1245184,
        "swapRead": 9,
        "swapReadSize": 589824,
        "swapReadTime": 14,
        "swapReadUncompressTime": 0,
        "swapWrite": 0,
        "swapWriteCompressTime": 0,
        "swapWriteSize": 0,
        "swapWriteTime": 0,
        "totalBackupLsn": 0,
        "totalLockConflictCount": 0,
        "totalOtherLsn": 0,
        "totalOwnerLsn": 66,
        "totalReadOperation": 0,
        "totalRowRead": 0,
        "totalRowWrite": 0,
        "totalWriteOperation": 0,
        "txnDetail": {
            "totalBackgroundOperation": 0
        }
    },
    "recovery": {
        "progressRate": 1
    },
    "version": "5.0.0-39331 CE"
}


```jsx
Properties props = new Properties();
//    props.setProperty("notificationAddress", "239.0.0.1");
//    props.setProperty("notificationPort", "31999");
 props.setProperty("host", "192.168.1.134");
 props.setProperty("port", "10001");
 props.setProperty("clusterName", "myCluster");
 props.setProperty("user", "admin");
 props.setProperty("password", "admin");
 props.setProperty("transactionTimeout","5000");
 props.setProperty("failoverTimeout","5000");
 GridStore store = GridStoreFactory.getInstance().getGridStore(props);

 Collection<String, Person> people = store.putCollection("person", Person.class);
 Person person = new Person();
 person.name = "name100";
 prson.status = false;
 person.count = 1;
 person.lob = new byte[] { 65, 66, 67, 68, 69, 70, 71, 72, 73, 74 };
 people.put(person.name,person);	// Registration
 people.commit();
 System.out.println("succcess");
```
com.toshiba.mwcloud.gs.common.GSConnectionException: [145028:JC_BAD_CONNECTION] Failed to connect (address=/127.0.0.1:10001, reason=Connection refused: connect)

**Comment by knonomura** [comment]
Thank you for your information.

Could you please  run gs_joincluster command with the IP address running GridDB server ?

gs_joincluster -c (your_clustername) -u (admin/your_password) -s (IP address)

**Comment by tom055** [comment]
gsadm@ubuntu:~$ gs_joincluster -c myCluster -u admin/admin -s 192.168.1.134
A70101: Node is already joined.

But still can't connect

Retry started (context=555590, statement=PUT_CONTAINER, orgAddress=null, partition=118, statementId=0, trialCount=0)
com.toshiba.mwcloud.gs.common.GSConnectionException: [145028:JC_BAD_CONNECTION] Failed to connect (address=/127.0.0.1:10001, reason=Connection refused: connect)

**Comment by knonomura** [comment]
Please restart GridDB server as below:

gs_stopcluster -u admin/admin
gs_stopnode -u admin/admin
gs_startnode
gs_joincluster -c myCluster -u admin/admin -s 192.168.1.134

And please confirm the address in the output of gs_stat command.

"master": {
"address": "192.168.1.134",<--
"port": 10040
},

**Comment by tom055** [comment]
This problem has been solved. Thank you.
