### ISSUE TITLE
How about the average calculation in the query interval

### ISSUE THREAD

**Issue by tom055** [griddb/griddb#400]
I want to get the average value of data in each interval. How do I query?
TIME_SAMPLING  and  TIME_AVG, How to merge them for query？
Thank you very much
![微信图片_20221226174134](https://user-images.githubusercontent.com/17687356/209533528-1c942be1-2ac4-4b53-8a9b-12bd84dfc7a1.png)

**Comment by joshua869** [comment]
Hello responsible griddb

**Comment by tom055** [comment]
I want to get the average value of the specified data field values in each interval, for example, the sum of data fields in each hour in a 24 hour day. I tried the following methods to get the data, but they failed to meet my needs. How do I get the desired results? Thank you.


gs[public]> tql lctime select * where timestamp < TIMESTAMPADD(HOUR, TIMESTAMP('2022-12-28T00:00:00Z'), -1) and timestamp > TIMESTAMPADD(HOUR, TIMESTAMP('2022-12-27T00:00:00Z'), -1)
362 results. (0 ms)
gs[public]> get 10
timestamp,data,temperature
2022-12-27T02:08:08.055Z,359.0,359.0
2022-12-27T02:34:00.105Z,359.0,359.0
2022-12-27T02:34:56.511Z,0.0,0.0
2022-12-27T02:35:56.511Z,1.0,1.0
2022-12-27T02:36:56.511Z,2.0,2.0
2022-12-27T02:37:56.511Z,3.0,3.0
2022-12-27T02:38:56.511Z,4.0,4.0
2022-12-27T02:39:56.511Z,5.0,5.0
2022-12-27T02:40:56.511Z,6.0,6.0
2022-12-27T02:41:56.511Z,7.0,7.0
The 10 results had been acquired.
gs[public]> tql lctime select sum(data) where timestamp < TIMESTAMPADD(HOUR, TIMESTAMP('2022-12-28T00:00:00Z'), -1) and timestamp > TIMESTAMPADD(HOUR, TIMESTAMP('2022-12-27T00:00:00Z'), -1);
1 results. (0 ms)
gs[public]> get 10
Result
65338.0
The 1 results had been acquired.

**Comment by knonomura** [comment]
Thank you for your usage.

(A) Using TQL (NoSQL interface)

You must use TQL with 24 selects.

Example:
SELECT avg(data) WHERE timestamp >= TIMESTAMP('2022-12-27T00:00:00Z') AND timestamp < TIMESTAMP('2022-12-27T01:00:00Z');
SELECT avg(data) WHERE timestamp >= TIMESTAMP('2022-12-27T01:00:00Z') AND timestamp < TIMESTAMP('2022-12-27T02:00:00Z');
...

(B) Using SQL (SQL interface)

Could you please use the nested SQL with timestamp_trunc() as below ?

Example:
SELECT key, avg(data) FROM (
  SELECT timestamp_trunc(hour, timestamp) key, data FROM tbl1
  WHERE timestamp >= TIMESTAMP('2022-12-27T00:00:00Z') AND
    timestamp < TIMESTAMP('2022-12-28T00:00:00Z')) t
  GROUP BY key;

GridDB SQL Reference
2.6.5.10 TIMESTAMP_TRUNC
https://github.com/griddb/docs-en/blob/master/manuals/GridDB_SQL_Reference.md#timestamp_trunc

**Comment by tom055** [comment]
Sorry for the late reply, but it seems that the interval can only be 1 minute and 1 hour. When I want the interval length to be customized, can this be achieved?

**Comment by Jeisankar** [comment]
I want to get the average value of the specified data field values in each interval, for example, the sum of data fields in each hour in a 24 hour day. I tried the following methods to get the data, but they failed to meet my needs. How do I get the desired results? Thank you. #413

**Comment by tom055** [comment]
@Jeisankar No implementation method found, other timing libraries have been sought to implement this functional requirement

**Comment by knonomura** [comment]
I have additional information about GridDB SQL.

The syntax "GROUP BY RANGE" has been added in GridDB SQL
as Aggregation/Interporation operator for timeseries data in GridDB V5.3.

How about this functionality ?

https://github.com/griddb/griddb/blob/master/docs/GridDB-5.3-CE-RELEASE_NOTES.md
>SQL Enhancement (Aggregation/Interporation operator for timeseries data)
>Time series data can now be grouped into time intervals and combined with 
>aggregation functions to extract the maximum, minimum, average, and total values of 
>these intervals. This function has been incorporated directly into GridDB to facilitate 
>and speed up time series data analysis as it eliminates the need to extract and 
>aggregate data on the application side. And a function that automatically interpolates 
>and fills in missing values using linear interpolation has been developed. This allows 
>for data continuity and enables highly accurate analysis and forecasting. 
>(This feature is currently supported by the JDBC driver.)
