### ISSUE TITLE
bin/gs_startnode  fail to start on version 4.3.0

### ISSUE THREAD

**Issue by tom055** [griddb/griddb#402]
System: ubuntu18.04
version:4.3.0     griddb-4.3.0.tar.gz

I tried to compile and install the 4.3.0 version on ubuntu18.04. After compiling and installing, execute bin/gs_ Startnode, the program has an error, and the python 2.7 version is used. Is it the Python version?

```jsx
wdgk@ubuntu:~/application/griddb/griddb-4.3.0$ bin/gs_startnode
Traceback (most recent call last):
  File "bin/gs_startnode", line 122, in <module>
    proc = subprocess.Popen(command, stdout=f, stderr=f)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by knonomura** [comment]
Thank you for your usage.

GridDB V4.6 or earlier: 
- Please use Python 2.7 for the operating commands.

GridDB V5.0 or later: 
- Please use Python 3 for the operating commands.

**Comment by tom055** [comment]
Thank you for your answer
