### ISSUE TITLE
Griddb Whether read/write splitting is supported？

### ISSUE THREAD

**Issue by tom055** [griddb/griddb#407]

**Comment by knonomura** [comment]
Thank you for your question.

GridDB supports eventual consistency.
https://github.com/griddb/docs-en/blob/master/manuals/GridDB_FeaturesReference.md#transaction-consistency-level

We can access only the original data in update operations.
On the other hand, we can access replica in read operations.

Does this answer your question?

**Comment by tom055** [comment]
Thank you very much for your reply
