### ISSUE TITLE
Berroe

### ISSUE THREAD

**Issue by Berro8** [griddb/griddb#429]
**Describe the bug**

**To Reproduce**
2. Type '....'
3. Execute '....'

**Expected behavior**

**Additional context**

**Comment by ROSISO** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Type '....'
> 3. Execute '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Additional context** Add any other context about the problem here. @Berro8

**Comment by DaniyalShabbir** [comment]
ok
