### ISSUE TITLE
Cannot `put` data into Partitioned Tables using Java NoSQL interface (Reading is OK)

### ISSUE THREAD

**Issue by Imisrael** [griddb/griddb#433]
**Describe the bug**
Trying to PUT data into a partitioned table using the Java NoSQL Interface results in an error. Querying is okay.

**To Reproduce**
Steps to reproduce the behavior: create a partitioned table and try to run some code against it. Querying works, pushing new data onto it does not.

**Expected behavior**
Expected behavior is to be able to put data into the partitioned table.

**Additional context**
Here is basic source code

```
import java.util.Arrays;
import java.util.Properties;
import java.util.Date;

import com.toshiba.mwcloud.gs.NotNull;
import com.toshiba.mwcloud.gs.Collection;
import com.toshiba.mwcloud.gs.GSException;
import com.toshiba.mwcloud.gs.GridStore;
import com.toshiba.mwcloud.gs.GridStoreFactory;
import com.toshiba.mwcloud.gs.Query;
import com.toshiba.mwcloud.gs.RowKey;
import com.toshiba.mwcloud.gs.RowSet;
import com.toshiba.mwcloud.gs.Container;
import com.toshiba.mwcloud.gs.Row;
import com.toshiba.mwcloud.gs.RowKeyPredicate;
import com.toshiba.mwcloud.gs.TimestampUtils;

public class Sample1 {

    static class RawLogInfo {
        @NotNull Date date;
        String value;
    }

    static Collection<String, RawLogInfo> col = null;

        public static void main(String[] args) throws GSException {

        Properties props = new Properties();
        props.setProperty("notificationMember", "127.0.0.1:10001");
        props.setProperty("clusterName", "myCluster");
        props.setProperty("user", "admin");
        props.setProperty("password", "admin");
        GridStore store = null;
                try{
                        store = GridStoreFactory.getInstance().getGridStore(props);
            col = store.getCollection("myIntervalPartition4", RawLogInfo.class);
                        if (col == null) {
                System.out.println("Container not found");
                                col.close();
                        }
            Query<RawLogInfo> query = col.query("select *");
            RowSet<RawLogInfo> rs = query.fetch(false);
            while (rs.hasNext()) {
                RawLogInfo row = rs.next();
                System.out.println(row.date + ": "  + row.value);
            }

            RawLogInfo row = new RawLogInfo();
            row.date = TimestampUtils.current();
            row.value = "testing";
            col.put(row);
            col.commit();


                } catch (Exception e) {
                        System.out.println("An error occurred when connecting to the server.");
                        e.printStackTrace();
                        System.exit(1);
                }

        }
}
```

Mon Sep 01 17:00:00 PDT 2025: test1
Thu Oct 26 14:35:42 PDT 2023: test2
Sun Sep 01 17:00:00 PDT 2024: test3
An error occurred when connecting to the server.
com.toshiba.mwcloud.gs.GSException: [145003:JC_UNSUPPORTED_OPERATION] Not supported on partitioned container
        at com.toshiba.mwcloud.gs.partitioned.PartContainer.errorNotSupported(PartContainer.java:708)
        at com.toshiba.mwcloud.gs.partitioned.PartContainer.commit(PartContainer.java:296)
        at com.toshiba.mwcloud.gs.partitioned.PartContainer$PartCollection.commit(PartContainer.java:713)
        at Sample1.main(Sample1.java:54)

**Comment by knonomura** [comment]
GridDB supports transaction only for simple table (container).
GridDB doesn't support transaction for Partitioned Tables.

So, we can't use commit/abort method for Partitioned Tables.

And I guess commit is unnecessary for this sample.
