### ISSUE TITLE
TABS ON MOBILE

### ISSUE THREAD

**Issue by AstroDEVg** [griddb/griddb#438]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Real d....
_________

AND THERES HAVE A TABS MOBILE VERSON DOWLAOD NOW HERES LINK
https://drive.google.com/file/d/1ZNSIqZbMSdVMCrc5uoFsgsz1z3-7AyI5/view?usp=drivesdk

**Comment by NorutoSDK** [comment]
IOS

**Comment by knonomura** [comment]
I close this issue as it is not related to griddb/griddb repository.
