### ISSUE TITLE
Agregar filtro de fecha en el listado de Riegos

### ISSUE THREAD

**Issue by fvillelagonzalez** [griddb/griddb#443]
Agregar dos campos  
Fecha inical
Fecha final

filtrar el listado de riegos en base a ese rango de fecha,

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb repository,
but I guess it is another topic.

**Comment by DeusArcana** [comment]
@knonomura 

I'm sorry guys, my collaborator posted this issue in the wrong repo. He is still learning about github. Cheers.

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
