### ISSUE TITLE
mov2mov插件在秋叶SD1.8版本上无法生成的问题

### ISSUE THREAD

**Issue by moma2046** [griddb/griddb#458]
mov2mov插件在秋叶1.8版本的SD上安装以后，点击生成按钮无效，后台也没有报错就停在那里，点击停止按钮也无效。总之就是生成视频没有任何反应。听说是mov2mov已经停止更新了，所以秋叶包1.8的版本上使用不了，但是有解决办法，谁能告诉我一下，谢谢

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb repository,
but I guess it is another topic.
So I close this issue.
