### ISSUE TITLE
Αντιστοίχιση

### ISSUE THREAD

**Issue by KonstantinaStelliou** [griddb/griddb#463]
**Describe the bug**
Παγωμένη οθόνη, δεν ανοίγει το παιχνίδι και όταν πατάω την επιλογή παύση δεν φαίνονται τα γράμματα.
<img width="1468" alt="αντιστοιχιση 3οεπιπεδο" src="https://github.com/griddb/griddb/assets/169995493/d433c2d9-d55a-4187-94a0-15f378c45fe6">

**3ο επίπεδο**

**To Reproduce**
2. Type '....'
3. Execute '....'

**Expected behavior**

**Additional context**

**Comment by BARON997** [comment]
https://bekesah.co/

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb repository,
I close this issue as it is not related to this repository.
